const SUPA_URL="https://iiumknzkjhiwtevpyavm.supabase.co";
const SUPA_KEY="sb_publishable_QnC0_AuecV4bhv4pzterwQ_W-Fl-ptc";
const PROJECT="salobo-infra-v6";
const API=SUPA_URL+'/rest/v1/project_execution_items';
let DATA={actions:[],subactions:[]}, P={macro:[],engenheiros:{Ligriarno:[],Leonardo:[],Kleber:[]}}, ST=new Map();
const names=['Macro','Ligriarno','Leonardo','Kleber'];
const equip={Ligriarno:[['MA84','17,7','26,0'],['MA82','23,2','34,9'],['MA83','23,5','34,8'],['MA85','31,0','44,6']],Leonardo:[['TT84','23,8','35,2'],['TT83','31,3','45,3'],['TT82','39,8','58,1']],Kleber:[['TT85','17,2','25,6'],['TT56','29,0','40,9'],['TT55','84,1','99,3'],['TT57','44,7','63,2']]};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function groupOf(a){const r=norm((a.responsible||'')+' '+(a.front||''));if(a.id&&/^M\d+$/.test(a.id))return 'Macro';if(r.includes('leonardo'))return 'Leonardo';if(r.includes('kleber'))return 'Kleber';return 'Ligriarno'}
function buildProject(){P={macro:[],engenheiros:{Ligriarno:[],Leonardo:[],Kleber:[]}};const byAct={};DATA.actions.forEach(a=>{const x={id:a.id,titulo:a.title||a.acao||'',tag:a.equipment||'MACRO',responsavel:a.responsible||'',front:a.front||'',subacoes:[]};byAct[x.id]=x;const g=groupOf(a);if(g==='Macro')P.macro.push(x);else P.engenheiros[g].push(x)});DATA.subactions.forEach(s=>{const a=byAct[s.action_id];if(a)a.subacoes.push({id:s.id,tipo:s.type||'',numero:s.number||'',descricao:s.description||'',responsavel:s.responsible||''})})}
const acts=n=>n==='Macro'?P.macro:(P.engenheiros[n]||[]);
const all=()=>names.flatMap(acts);
const subDone=s=>ST.get(s.id)==='DONE';
const actionDone=a=>{const ss=a.subacoes||[];return ss.length?ss.every(subDone):ST.get(a.id)==='DONE'};
function units(arr){let total=0,done=0;arr.forEach(a=>{const ss=a.subacoes||[];if(ss.length){total+=ss.length;done+=ss.filter(subDone).length}else{total++;if(actionDone(a))done++}});return {total,done,pct:total?Math.round(done*100/total):0}}
const pct=n=>units(acts(n)).pct;
function chart(n,mini=false){let v=n==='Geral'?units(all()).pct:pct(n),w=mini?330:850,h=mini?88:145;return `<svg class="${mini?'miniChart':'chart'}" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><line class="grid" x1="30" y1="${h-20}" x2="${w-8}" y2="${h-20}"/><line class="grid" x1="30" y1="15" x2="${w-8}" y2="15"/><path class="plan" d="M32 ${h-20} C${w*.25} ${h-19},${w*.26} ${h*.54},${w*.48} ${h*.48} S${w*.68} 15,${w-10} 15"/><path class="real" d="M32 ${h-20} L${w*.18} ${h-20-v*(h-35)/100}"/><circle cx="${w*.18}" cy="${h-20-v*(h-35)/100}" r="4" fill="var(--g)"/><line class="today" x1="${w*.18}" y1="10" x2="${w*.18}" y2="${h-18}"/><text class="axis" x="3" y="${h-16}">0%</text><text class="axis" x="1" y="19">100%</text><text class="axis" x="${w*.18+7}" y="${h-25-v*(h-35)/100}">${v}%</text><text class="axis" x="30" y="${h-3}">20/08</text><text class="axis" x="${w*.45}" y="${h-3}">19/09</text><text class="axis" x="${w*.83}" y="${h-3}">19/11</text></svg>`}
function renderHome(){const A=all(),u=units(A);document.getElementById('kActs').textContent=A.length;document.getElementById('kSubs').textContent=DATA.subactions.length;document.getElementById('kDone').textContent=A.filter(actionDone).length;document.getElementById('kPct').textContent=u.pct+'%';document.getElementById('globalChart').innerHTML=chart('Geral');document.getElementById('summary').innerHTML=names.map(n=>{let z=units(acts(n));return `<div class="sum"><b>${z.pct}%</b><span>${n}<br>${z.done}/${z.total} unidades</span></div>`}).join('');document.getElementById('groups').innerHTML=names.map(group).join('')}
function group(n){if(n==='Macro')return `<article class="group"><div class="gh"><div class="macroIcon">M</div><div><h3>MACRO</h3><p>ações transversais do projeto</p></div></div><div class="macroList">${acts(n).map((a,i)=>`<div class="actionline"><span>${i+1}. ${esc(a.titulo)}</span><span>${actionDone(a)?'OK':'ABERTA'}</span></div>`).join('')}</div><div class="actionsmini">${chart(n,true)}</div></article>`;let rows=(equip[n]||[]).map(x=>`<div class="fleetrow"><b>${x[0]}</b><div class="bar"><i style="width:${Math.round(100*(+x[1].replace(',','.')/+x[2].replace(',','.')))}%"></i></div><span>${x[1]}→${x[2]} h</span></div>`).join('');let extra=n==='Ligriarno'?'<div class="fleetrow"><b>24/24M</b><div class="bar"><i style="width:'+pct(n)+'%"></i></div><span>freios integrados</span></div>':'';return `<article class="group"><div class="gh"><div class="machine">${n==='Ligriarno'?'24M':'D11'}</div><div><h3>${n}</h3><p>${acts(n).length} ações integradas</p></div></div><div class="fleet">${rows+extra}</div><div class="actionsmini"><div class="ph"><h2>Curva S da execução</h2><small>${units(acts(n)).done}/${units(acts(n)).total}</small></div>${chart(n,true)}</div></article>`}
function buildDetails(){document.getElementById('details').innerHTML=names.map(n=>`<section id="page-${n}" class="screen detail"><header class="top"><div><div class="brand">SOTREQ</div><h1>${n==='Macro'?'Ações MACRO':'Plano detalhado — '+n}</h1><div class="meta">Ações e subações do projeto · somente leitura</div></div><nav class="nav"><button onclick="show('home')">Visão geral</button>${names.map(x=>`<button class="${x===n?'on':''}" onclick="show('${x}')">${x}</button>`).join('')}</nav></header><main class="detailmain"><div class="detailhead"><div><h2>${n}</h2><p>${n==='Macro'?'Ações transversais do projeto.':'Execução detalhada por ação e subação.'}</p></div><div class="progress" id="p-${n}">${pct(n)}%</div></div><div class="${n==='Macro'?'macroActions':''}" id="list-${n}"></div></main></section>`).join('');names.forEach(renderDetail)}
function renderDetail(n){let el=document.getElementById('list-'+n);if(!el)return;el.innerHTML=acts(n).map((a,i)=>{let ss=a.subacoes||[],rows=ss.map(s=>`<tr><td><input class="subcheck" type="checkbox" ${subDone(s)?'checked':''} disabled></td><td><b>${esc(s.tipo)}</b></td><td>${esc(s.numero||'—')}</td><td>${esc(s.descricao)}</td><td>${esc(s.responsavel||a.responsavel||'—')}</td></tr>`).join('');return `<article class="actioncard"><div class="actiontitle"><input type="checkbox" ${actionDone(a)?'checked':''} disabled><span class="pill">${esc(a.tag||'MACRO')}</span><h3>${i+1}. ${esc(a.titulo)}</h3><small>${ss.length} subações</small></div>${ss.length?`<div class="submeta">As baixas são registradas pelos engenheiros nos apps e refletidas automaticamente aqui.</div><div class="tablewrap"><table><thead><tr><th>OK</th><th>Tipo</th><th>Nº BL/Nota</th><th>Descrição</th><th>Responsável</th></tr></thead><tbody>${rows}</tbody></table></div>`:`<div class="empty">Ação sem subação vinculada.</div>`}</article>`}).join('');let p=document.getElementById('p-'+n);if(p)p.textContent=pct(n)+'%'}
function show(n){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.getElementById(n==='home'?'home':'page-'+n).classList.add('active');if(n!=='home')renderDetail(n);window.scrollTo(0,0)}
async function loadData(){const r=await fetch('../cliente/index.html',{cache:'no-store'});if(!r.ok)throw Error('Não foi possível carregar a base do projeto');const t=await r.text();let m=t.match(/const DATA=(\{.*\});\s*const KEY=/s);if(!m)m=t.match(/const DATA=(\{.*\});\s*let S=/s);if(!m)throw Error('Estrutura DATA não localizada no app');DATA=JSON.parse(m[1]);buildProject();buildDetails()}
async function refreshStatus(){try{const r=await fetch(API+'?project_key=eq.'+encodeURIComponent(PROJECT)+'&select=item_id,status,updated_at',{headers:{apikey:SUPA_KEY},cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const rows=await r.json();ST=new Map(rows.map(x=>[x.item_id,x.status]));renderHome();names.forEach(renderDetail);const d=document.getElementById('syncDot');d.className='syncdot ok';document.getElementById('syncText').textContent='Atualizado '+new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}catch(e){const d=document.getElementById('syncDot');d.className='syncdot err';document.getElementById('syncText').textContent='Falha de atualização automática'}}
(async()=>{try{await loadData();await refreshStatus();setInterval(refreshStatus,15000)}catch(e){document.getElementById('syncDot').className='syncdot err';document.getElementById('syncText').textContent=e.message}})();
