const SUPA_URL="https://iiumknzkjhiwtevpyavm.supabase.co";
const SUPA_KEY="sb_publishable_QnC0_AuecV4bhv4pzterwQ_W-Fl-ptc";
const PROJECT="salobo-infra-v6";
const API=SUPA_URL+'/rest/v1/project_execution_items';
let DATA={actions:[],subactions:[]}, P={macro:[],engenheiros:{Ligriarno:[],Leonardo:[],Kleber:[]}}, ST=new Map(), UPDATED=new Map(), SCHEDULE=null;
const names=['Macro','Ligriarno','Leonardo','Kleber'];
const engineerNames=['Ligriarno','Leonardo','Kleber'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const fmtDate=iso=>iso?new Date(iso+'T12:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'}):'—';
const parseDate=iso=>iso?new Date(iso+'T12:00:00'):null;
function groupOf(a){const r=norm((a.responsible||'')+' '+(a.front||''));if(a.id&&/^M\d+$/.test(a.id))return 'Macro';if(r.includes('leonardo'))return 'Leonardo';if(r.includes('kleber'))return 'Kleber';return 'Ligriarno'}
function buildProject(){P={macro:[],engenheiros:{Ligriarno:[],Leonardo:[],Kleber:[]}};const byAct={};DATA.actions.forEach(a=>{const x={id:a.id,titulo:a.title||a.acao||'',tag:a.equipment||'MACRO',responsavel:a.responsible||'',front:a.front||'',raw:a,subacoes:[]};byAct[x.id]=x;const g=groupOf(a);if(g==='Macro')P.macro.push(x);else P.engenheiros[g].push(x)});DATA.subactions.forEach(s=>{const a=byAct[s.action_id];if(a)a.subacoes.push({id:s.id,tipo:s.type||'',numero:s.number||'',descricao:s.description||'',responsavel:s.responsible||'',equipment:s.equipment||'',raw:s})})}
const acts=n=>n==='Macro'?P.macro:(P.engenheiros[n]||[]);
const all=()=>names.flatMap(acts);
const operational=()=>engineerNames.flatMap(acts);
const subDone=s=>ST.get(s.id)==='DONE';
const actionDone=a=>{const ss=a.subacoes||[];return ss.length?ss.every(subDone):ST.get(a.id)==='DONE'};
function units(arr){let total=0,done=0;arr.forEach(a=>{const ss=a.subacoes||[];if(ss.length){total+=ss.length;done+=ss.filter(subDone).length}else{total++;if(actionDone(a))done++}});return {total,done,pct:total?Math.round(done*100/total):0}}
const pct=n=>units(acts(n)).pct;
function executionUnits(arr){const out=[];arr.forEach(a=>{const ss=a.subacoes||[];if(ss.length)ss.forEach(s=>out.push({id:s.id,action:a,sub:s,done:subDone(s)}));else out.push({id:a.id,action:a,sub:null,done:actionDone(a)})});return out}
function scheduleGroup(n){return SCHEDULE?.groups?.[n]||null}
function knownTags(n){return (scheduleGroup(n)?.machines||[]).map(m=>m.tag)}
function extractTags(text,n){const up=String(text||'').toUpperCase();return knownTags(n).filter(t=>up.includes(t))}
function plannedDateForUnit(u,n){const sg=scheduleGroup(n);if(!sg)return null;let text=[u.sub?.equipment,u.sub?.numero,u.sub?.descricao,u.action?.tag,u.action?.titulo].filter(Boolean).join(' ');let tags=extractTags(text,n);if(!tags.length&&u.action?.tag)tags=extractTags(u.action.tag,n);if(!tags.length){return sg.cycle_close||null}const ds=tags.map(t=>sg.machines.find(m=>m.tag===t)?.stop_date).filter(Boolean).sort();if(ds.length!==tags.length)return null;return ds[ds.length-1]}
function curveUnits(n){const arr=n==='Geral'?operational():acts(n);return executionUnits(arr)}
function actualCompletionDate(u){const raw=UPDATED.get(u.id);if(!raw)return null;const d=new Date(raw);return isNaN(d)?null:d}
function buildSeries(n,kind){const us=curveUnits(n),total=us.length;if(!total)return[];const start=parseDate(SCHEDULE?.chart_start||'2026-09-16');const end=parseDate(SCHEDULE?.chart_end||'2026-11-10');let events=[];
 if(kind==='plan')us.forEach(u=>{const g=n==='Geral'?groupOf(u.action.raw):n;const d=plannedDateForUnit(u,g);if(d)events.push({d:parseDate(d),id:u.id})});
 else us.filter(u=>u.done).forEach(u=>{let d=actualCompletionDate(u)||new Date();if(d<start)d=start;events.push({d,id:u.id})});
 events=events.filter(x=>x.d&&x.d<=end).sort((a,b)=>a.d-b.d);let pts=[{d:start,pct:0}],done=0,i=0;while(i<events.length){const when=events[i].d;let c=0;while(i<events.length&&events[i].d.toDateString()===when.toDateString()){c++;i++}done+=c;pts.push({d:when,pct:Math.round(done*1000/total)/10})}const current=kind==='real'?new Date():end;if(current>=start){const capped=current>end?end:current;if(!pts.length||pts[pts.length-1].d<capped)pts.push({d:capped,pct:pts[pts.length-1]?.pct||0})}return pts}
function pathStep(points,x,y){if(!points.length)return'';let d=`M${x(points[0].d)} ${y(points[0].pct)}`;for(let i=1;i<points.length;i++){d+=` H${x(points[i].d)} V${y(points[i].pct)}`}return d}
function chartTicks(start,end,count){const span=end-start;return Array.from({length:count},(_,i)=>new Date(start.getTime()+span*(i/(count-1))))}
function chart(n,mini=false){
 const w=mini?420:960,h=mini?132:220,padL=mini?38:48,padR=mini?14:22,padT=18,padB=mini?38:52;
 const start=parseDate(SCHEDULE?.chart_start||'2026-09-16'),end=parseDate(SCHEDULE?.chart_end||'2026-11-10'),span=Math.max(1,end-start);
 const x=d=>padL+((d-start)/span)*(w-padL-padR),y=p=>padT+(100-p)/100*(h-padT-padB);
 const plan=buildSeries(n,'plan'),real=buildSeries(n,'real');
 const pv=plan.length?plan[plan.length-1].pct:0,rv=units(n==='Geral'?operational():acts(n)).pct;
 let today=new Date();if(today<start)today=start;if(today>end)today=end;
 const close=n==='Geral'?SCHEDULE?.overall?.cycle_close:scheduleGroup(n)?.cycle_close;
 const pend=n==='Geral'?(SCHEDULE?.overall?.pending||[]):(scheduleGroup(n)?.pending||[]);
 const ticks=chartTicks(start,end,mini?3:5);
 const tickGrid=ticks.map(d=>`<line class="xgrid" x1="${x(d)}" y1="${padT}" x2="${x(d)}" y2="${h-padB}"/>`).join('');
 const tickLabels=ticks.map((d,i)=>{const anchor=i===0?'start':i===ticks.length-1?'end':'middle';return `<text class="axis ${mini?'miniAxis':''}" text-anchor="${anchor}" x="${x(d)}" y="${h-12}">${d.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})}</text>`}).join('');
 return `<div style="display:flex;gap:10px;align-items:center;flex-wrap:wrap;font-size:10px;color:#707177;margin:2px 0 5px"><span><i style="display:inline-block;width:18px;border-top:2px dashed #a6a8ac;margin-right:4px;vertical-align:middle"></i>Programação ${pv}%</span><span><i style="display:inline-block;width:18px;border-top:3px solid var(--g);margin-right:4px;vertical-align:middle"></i>Execução ${rv}%</span><span>${close?'Fechamento '+fmtDate(close):(pend.length?'Fechamento pendente: '+pend.join(', '):'')}</span></div><svg class="${mini?'miniChart':'chart'}" viewBox="0 0 ${w} ${h}" role="img" aria-label="Curva de programação e execução"><line class="grid" x1="${padL}" y1="${y(0)}" x2="${w-padR}" y2="${y(0)}"/><line class="grid" x1="${padL}" y1="${y(50)}" x2="${w-padR}" y2="${y(50)}"/><line class="grid" x1="${padL}" y1="${y(100)}" x2="${w-padR}" y2="${y(100)}"/>${tickGrid}<path class="plan" d="${pathStep(plan,x,y)}"/><path class="real" d="${pathStep(real,x,y)}"/><line class="today" x1="${x(today)}" y1="${padT-4}" x2="${x(today)}" y2="${h-padB+3}"/><text class="axis" text-anchor="end" x="${padL-7}" y="${y(0)+4}">0%</text><text class="axis" text-anchor="end" x="${padL-7}" y="${y(50)+4}">50%</text><text class="axis" text-anchor="end" x="${padL-7}" y="${y(100)+4}">100%</text>${tickLabels}</svg>`
}
function cycleText(n){const sg=scheduleGroup(n);if(!sg)return'—';if(sg.cycle_close)return fmtDate(sg.cycle_close);return 'Pendente '+(sg.pending||[]).join(', ')}
function fleetRows(n){const sg=scheduleGroup(n);if(!sg)return'';const start=parseDate(SCHEDULE.chart_start),end=parseDate(SCHEDULE.chart_end),span=end-start;return sg.machines.map(m=>{let d=m.stop_date?parseDate(m.stop_date):null;let width=d?Math.max(4,Math.min(100,((d-start)/span)*100)):0;let label=m.stop_date?fmtDate(m.stop_date):'sem data';let qual=m.date_quality==='ESTIMADA_FIM_SEMANA'?'estimada':m.date_quality==='DATA_PLANEJADA'?'planejada':'pendente';return `<div class="fleetrow"><b>${m.tag}</b><div class="bar"><i style="width:${width}%"></i></div><span>${label} · ${qual}</span></div>`}).join('')}
function renderHome(){const A=all(),op=operational(),u=units(op);document.getElementById('kActs').textContent=A.length;document.getElementById('kSubs').textContent=DATA.subactions.length;const kDone=document.getElementById('kDone');if(kDone)kDone.textContent=SCHEDULE?.overall?.cycle_close?fmtDate(SCHEDULE.overall.cycle_close):'Pendente TT85';document.getElementById('kPct').textContent=u.pct+'%';document.getElementById('globalChart').innerHTML=chart('Geral');document.getElementById('summary').innerHTML=engineerNames.map(n=>{let z=units(acts(n));return `<div class="sum"><b>${z.pct}%</b><span>${scheduleGroup(n)?.label||n}<br>${z.done}/${z.total} unidades<br>1º ciclo: ${cycleText(n)}</span></div>`}).join('')+`<div class="sum"><b>${units(P.macro).pct}%</b><span>Macro<br>${units(P.macro).done}/${units(P.macro).total} unidades<br>fora da curva operacional</span></div>`;document.getElementById('groups').innerHTML=names.map(group).join('')}
function group(n){if(n==='Macro')return `<article class="group"><div class="gh"><div class="macroIcon">M</div><div><h3>MACRO</h3><p>ações transversais · fora da curva de paradas</p></div></div><div class="macroList">${acts(n).map((a,i)=>`<div class="actionline"><span>${i+1}. ${esc(a.titulo)}</span><span>${actionDone(a)?'OK':'ABERTA'}</span></div>`).join('')}</div><div class="actionsmini"><div class="ph"><h2>Execução Macro</h2><small>${units(acts(n)).done}/${units(acts(n)).total}</small></div></div></article>`;let label=scheduleGroup(n)?.label||n;return `<article class="group"><div class="gh"><div class="machine">${n==='Ligriarno'?'24M':'D11'}</div><div><h3>${label}</h3><p>${acts(n).length} ações · 1º ciclo ${cycleText(n)}</p></div></div><div class="fleet">${fleetRows(n)}</div><div class="actionsmini"><div class="ph"><h2>Programação × execução</h2><small>${units(acts(n)).done}/${units(acts(n)).total} unidades</small></div>${chart(n,true)}</div></article>`}
function buildDetails(){document.getElementById('details').innerHTML=names.map(n=>`<section id="page-${n}" class="screen detail"><header class="top"><div><div class="brand">SOTREQ</div><h1>${n==='Macro'?'Ações MACRO':'Plano detalhado — '+(scheduleGroup(n)?.label||n)}</h1><div class="meta">Ações e subações do projeto · somente leitura</div></div><nav class="nav"><button onclick="show('home')">Visão geral</button>${names.map(x=>`<button class="${x===n?'on':''}" onclick="show('${x}')">${scheduleGroup(x)?.label||x}</button>`).join('')}</nav></header><main class="detailmain"><div class="detailhead"><div><h2>${scheduleGroup(n)?.label||n}</h2><p>${n==='Macro'?'Ações transversais do projeto.':`Programação do 1º ciclo: ${cycleText(n)} · execução medida por ações/subações.`}</p></div><div class="progress" id="p-${n}">${pct(n)}%</div></div>${n==='Macro'?'':`<article class="actioncard"><div class="actiontitle" style="grid-template-columns:1fr"><h3>Programação × execução do 1º ciclo</h3></div><div style="padding:10px 14px">${chart(n,false)}</div></article>`}<div class="${n==='Macro'?'macroActions':''}" id="list-${n}"></div></main></section>`).join('');names.forEach(renderDetail)}
function renderDetail(n){let el=document.getElementById('list-'+n);if(!el)return;el.innerHTML=acts(n).map((a,i)=>{let ss=a.subacoes||[],rows=ss.map(s=>`<tr><td><input class="subcheck" type="checkbox" ${subDone(s)?'checked':''} disabled></td><td><b>${esc(s.tipo)}</b></td><td>${esc(s.numero||'—')}</td><td>${esc(s.descricao)}</td><td>${esc(s.responsavel||a.responsavel||'—')}</td></tr>`).join('');return `<article class="actioncard"><div class="actiontitle"><input type="checkbox" ${actionDone(a)?'checked':''} disabled><span class="pill">${esc(a.tag||'MACRO')}</span><h3>${i+1}. ${esc(a.titulo)}</h3><small>${ss.length} subações</small></div>${ss.length?`<div class="submeta">As baixas são registradas pelos engenheiros nos apps e refletidas automaticamente aqui.</div><div class="tablewrap"><table><thead><tr><th>OK</th><th>Tipo</th><th>Nº BL/Nota</th><th>Descrição</th><th>Responsável</th></tr></thead><tbody>${rows}</tbody></table></div>`:`<div class="empty">Ação sem subação vinculada.</div>`}</article>`}).join('');let p=document.getElementById('p-'+n);if(p)p.textContent=pct(n)+'%'}
function show(n){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.getElementById(n==='home'?'home':'page-'+n).classList.add('active');if(n!=='home')renderDetail(n);window.scrollTo(0,0)}
async function loadData(){const [r,sr]=await Promise.all([fetch('../cliente/index.html',{cache:'no-store'}),fetch('../project_schedule.json',{cache:'no-store'})]);if(!r.ok)throw Error('Não foi possível carregar a base do projeto');if(!sr.ok)throw Error('Não foi possível carregar a programação');const t=await r.text();let m=t.match(/const DATA=(\{.*\});\s*const KEY=/s);if(!m)m=t.match(/const DATA=(\{.*\});\s*let S=/s);if(!m)throw Error('Estrutura DATA não localizada no app');DATA=JSON.parse(m[1]);SCHEDULE=await sr.json();buildProject();buildDetails()}
async function refreshStatus(){try{const r=await fetch(API+'?project_key=eq.'+encodeURIComponent(PROJECT)+'&select=item_id,status,updated_at',{headers:{apikey:SUPA_KEY},cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const rows=await r.json();ST=new Map(rows.map(x=>[x.item_id,x.status]));UPDATED=new Map(rows.map(x=>[x.item_id,x.updated_at]));renderHome();names.forEach(renderDetail);const d=document.getElementById('syncDot');d.className='syncdot ok';document.getElementById('syncText').textContent='Atualizado '+new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}catch(e){const d=document.getElementById('syncDot');d.className='syncdot err';document.getElementById('syncText').textContent='Falha de atualização automática'}}
(async()=>{try{await loadData();await refreshStatus();setInterval(refreshStatus,15000)}catch(e){document.getElementById('syncDot').className='syncdot err';document.getElementById('syncText').textContent=e.message}})();