(()=>{
'use strict';
const SUPA='https://iiumknzkjhiwtevpyavm.supabase.co';
const KEYAPI='sb_publishable_QnC0_AuecV4bhv4pzterwQ_W-Fl-ptc';
const PROJECT='salobo-infra-v6';
const API=SUPA+'/rest/v1/project_execution_items';
const CUTOVER=new Date('2026-09-16T19:00:00Z');
let SCH=null, ROWS=new Map(), busy=false;
const hdr={apikey:KEYAPI,'Content-Type':'application/json'};
const pd=s=>s?new Date(s+'T12:00:00'):null;
const fd=d=>d?d.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'}):'—';
const isoDay=d=>d?d.toISOString().slice(0,10):null;
const machineDates=()=>{const out=[];if(!SCH)return out;Object.entries(SCH.groups||{}).forEach(([g,v])=>(v.machines||[]).forEach(m=>{if(m.stop_date)out.push({tag:m.tag,date:m.stop_date,group:g,quality:m.date_quality})}));return out.sort((a,b)=>a.date.localeCompare(b.date));};
const stopForTag=tag=>machineDates().find(x=>x.tag===tag)?.date||null;
const unitList=arr=>{const out=[];(arr||[]).forEach(a=>{const ss=subsFor(a.id);if(ss.length)ss.forEach(s=>out.push({id:s.id,a,s}));else out.push({id:a.id,a,s:null})});return out;};
function planDate(u,brake){
 if(brake){const bt=D.brake_timeline||[];const txt=[u.a.equipment,u.a.title,u.s?.description,u.s?.equipment].filter(Boolean).join(' ').toUpperCase();const hit=bt.find(x=>txt.includes(x.tag));if(hit)return hit.replacement_date.split('/').reverse().join('-');return D.brake_metrics?.finish_pt?.split('/').reverse().join('-')||'2027-01-14';}
 if(u.a.front==='Macro')return u.a.due_iso||null;
 const tag=String(u.a.equipment||'').trim().toUpperCase();const direct=stopForTag(tag);if(direct)return direct;
 const txt=[u.a.equipment,u.a.title,u.s?.description,u.s?.equipment].filter(Boolean).join(' ').toUpperCase();const hits=machineDates().filter(x=>txt.includes(x.tag));if(hits.length)return hits.sort((a,b)=>a.date.localeCompare(b.date)).at(-1).date;
 if(u.a.project_type==='FREIOS')return '2027-01-14';return null;
}
function rowDone(id){return ROWS.get(id)?.status==='DONE'}
function remotePct(arr){const us=unitList(arr);return us.length?Math.round(us.filter(u=>rowDone(u.id)).length*100/us.length):0}
function series(arr,kind,brake,start,end){const us=unitList(arr),total=us.length;if(!total)return[];let ev=[],baseline=0;if(kind==='plan'){us.forEach(u=>{const ds=planDate(u,brake);const d=pd(ds);if(d)ev.push(d)});}else{us.forEach(u=>{const r=ROWS.get(u.id);if(!r||r.status!=='DONE')return;const d=new Date(r.updated_at);if(!r.updated_at||isNaN(d)||d<=CUTOVER||d<start)baseline++;else ev.push(d)});}ev=ev.filter(d=>d<=end).sort((a,b)=>a-b);const pts=[{d:start,pct:Math.round(baseline*1000/total)/10}];let done=baseline,i=0;while(i<ev.length){const day=isoDay(ev[i]);let c=0,when=ev[i];while(i<ev.length&&isoDay(ev[i])===day){c++;i++}done+=c;pts.push({d:when,pct:Math.round(done*1000/total)/10})}const tail=kind==='real'?new Date():end,cap=tail>end?end:(tail<start?start:tail);if(pts.at(-1).d<cap)pts.push({d:cap,pct:pts.at(-1).pct});return pts;}
function spath(pts,x,y){if(!pts.length)return'';let s=`M${x(pts[0].d)} ${y(pts[0].pct)}`;for(let i=1;i<pts.length;i++)s+=` H${x(pts[i].d)} V${y(pts[i].pct)}`;return s}
function marks(brake){if(brake)return (D.brake_timeline||[]).map(x=>({tag:x.tag,date:x.replacement_date.split('/').reverse().join('-'),quality:x.condition}));return machineDates();}
function liveChart(arr,mini=false,brake=false){const ms=marks(brake);let start=brake?pd('2026-09-11'):pd(SCH?.chart_start||'2026-09-16');let end=brake?pd('2027-01-14'):pd(SCH?.chart_end||'2026-11-10');if(!mini&&!brake)end=pd('2027-01-14');const w=mini?360:900,h=mini?118:205,L=38,R=12,T=mini?20:34,B=28,span=Math.max(1,end-start);const x=d=>L+Math.max(0,Math.min(1,(d-start)/span))*(w-L-R),y=p=>T+(100-p)/100*(h-T-B);const plan=series(arr,'plan',brake,start,end),real=series(arr,'real',brake,start,end);const planv=plan.at(-1)?.pct||0,realv=remotePct(arr),now=new Date(),tn=now<start?start:(now>end?end:now);let msvg='';ms.filter(m=>{const d=pd(m.date);return d>=start&&d<=end}).forEach((m,i)=>{const d=pd(m.date),xx=x(d),yy=mini?10:(i%2?22:11);msvg+=`<line x1="${xx}" y1="${T}" x2="${xx}" y2="${h-B}" stroke="#d8d8d8" stroke-width="1"/><text x="${xx+2}" y="${yy}" fill="#555" font-size="${mini?7:8}">${m.tag} ${fd(d)}</text>`});const base=real.length?real[0].pct:0;return `<svg class="${mini?'miniChart':'chart'}" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><line class="gridline" x1="${L}" y1="${y(0)}" x2="${w-R}" y2="${y(0)}"/><line class="gridline" x1="${L}" y1="${y(100)}" x2="${w-R}" y2="${y(100)}"/>${msvg}<path class="plan" d="${spath(plan,x,y)}"/><path class="real" d="${spath(real,x,y)}"/><line class="today" x1="${x(tn)}" y1="${T-5}" x2="${x(tn)}" y2="${h-B+3}"/><text class="axis" x="3" y="${y(0)+4}">0%</text><text class="axis" x="1" y="${y(100)+4}">100%</text><text x="${L+4}" y="${T+12}" fill="#17814c" font-size="${mini?8:10}" font-weight="700">Exec. ${realv}%${base?' · base importada '+base+'%':''}</text><text x="${L+100}" y="${T+12}" fill="#888" font-size="${mini?8:10}">Prog. conhecida ${planv}%</text><text class="axis" x="${L}" y="${h-5}">${fd(start)}</text><text class="axis" x="${w-50}" y="${h-5}">${fd(end)}</text></svg>`;}
async function pull(){if(busy)return;busy=true;try{const [rr,sr]=await Promise.all([fetch(API+'?project_key=eq.'+encodeURIComponent(PROJECT)+'&select=item_id,item_type,status,updated_at',{headers:hdr,cache:'no-store'}),SCH?Promise.resolve(null):fetch('project_schedule.json?v=7',{cache:'no-store'})]);if(!rr.ok)throw Error('Base compartilhada HTTP '+rr.status);if(sr&&!sr.ok)throw Error('Programação HTTP '+sr.status);if(sr)SCH=await sr.json();const rows=await rr.json();ROWS=new Map(rows.map(r=>[r.item_id,r]));D.subactions.forEach(s=>{const r=ROWS.get(s.id);if(r)S.sub[s.id]=r.status==='DONE'});D.actions.forEach(a=>{const r=ROWS.get(a.id);if(r&&!subsFor(a.id).length)S.done[a.id]=r.status==='DONE'});save();sChart=liveChart;renderHome();buildDetails();const title=document.querySelector('#home .global .ph h2');if(title)title.textContent='Curva S principal — programação por máquina × execução dos apps';const small=document.querySelector('#home .global .ph small');if(small)small.textContent='datas das paradas marcadas · execução sincronizada a cada 15 s';let badge=document.getElementById('live-sync-v7');if(!badge){badge=document.createElement('div');badge.id='live-sync-v7';badge.style.cssText='position:fixed;right:12px;bottom:10px;z-index:20;background:#171717;color:#fff;border-left:5px solid #20a66a;padding:7px 10px;font:11px Arial';document.body.appendChild(badge)}badge.textContent='Base compartilhada: '+rows.filter(r=>r.item_type==='SUBACTION'&&r.status==='DONE').length+' subações concluídas · '+new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});}catch(e){console.warn('Live V7',e)}finally{busy=false}}
async function patch(id,status){const r=await fetch(API+'?project_key=eq.'+encodeURIComponent(PROJECT)+'&item_id=eq.'+encodeURIComponent(id),{method:'PATCH',headers:{...hdr,Prefer:'return=minimal'},body:JSON.stringify({status,updated_at:new Date().toISOString()})});if(!r.ok)throw Error('PATCH '+r.status)}
const oldDone=done,oldSub=subDone;
done=async function(id,v){oldDone(id,v);const a=D.actions.find(x=>x.id===id),ss=a?subsFor(id):[];try{if(ss.length)await Promise.all(ss.map(x=>patch(x.id,v?'DONE':'OPEN')));else await patch(id,v?'DONE':'OPEN');await pull()}catch(e){console.warn(e)}};
subDone=async function(id,v){oldSub(id,v);try{await patch(id,v?'DONE':'OPEN');await pull()}catch(e){console.warn(e)}};
openFreios=function(){window.open('24/Visao_Gerencial_Freios_24_24M_V6.html?v=live7','_blank')};
pull();setInterval(pull,15000);window.addEventListener('online',pull);
})();
